export interface Coin {
    id: string,
    symbol: string,
    name: string,
    image: string,
    current_price: number,
    market_cap: number,
    market_cap_rank: number,
    fully_diluted_valuation: number,
    total_volume: number,
    high_24h: number,
    low_24h: number,
    price_change_24h: number,
    price_change_percentage_24h: number,
    market_cap_change_24h: number,
    market_cap_change_percentage_24h: number,
    circulating_supply: number,
    total_supply: number,
    max_supply: number,
    ath: number,
    ath_change_percentage: number,
    ath_date: Date,
    atl: number,
    atl_change_percentage: number,
    atl_date: Date,
    roi: string,
    last_updated: Date,
    sparkline_in_7d?: { price: number[]}
}

export interface GlobalData {
    active_cryptocurrencies: number,
    markets: number,
    total_market_cap: Record<string, number>,
    total_volume: Record<string, number>,
    market_cap_percentage: Record<string, number>,
    market_cap_change_percentage_24h_usd: number,
    updated_at: number,
    upcoming_icos: number,
    ongoing_icos: number,
    ended_icos: number
}